theme: jekyll-theme-minimal
title: Erik Stacey
description: Hello! I'm a student of stellar physics, a developer of scientific analysis tools, and appreciator of fine keyboards. You can find more information about my professional skills and personal life here.
